name: tack_habit
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.0.0
  google_fonts: ^2.0.0
  animated_bottom_navigation_bar: ^0.2.1
  rich_alert: ^0.1.32
  provider: ^5.0.0
  cloud_firestore: ^1.0.0
  firebase_core: ^1.0.0
  firebase_auth: ^1.0.0
  rflutter_alert: ^1.1.0
  shared_preferences: ^2.0.3
  flutter_zoom_drawer: ^1.0.4+1
  cupertino_icons: ^0.1.2
  animated_text_kit: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.0.0
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.0.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/appIcon.png"

flutter_native_splash:
  color: "#545454"
  image: assets/splashIcon.png

flutter:
  uses-material-design: true
